server:
  port: 8787
  servlet:
    context-path: /webhook

spring:
  application:
    name: @artifactId@
  banner:
    location: banner.txt
config:
  webhooks:
    - id: finance
      type: GITLAB
      conf:
        gitlab:
          host: http://192.168.10.1:8080/
          private-token: xxxxxxx
      notify:
        ding-talk:
          access-token: "93axxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx83c"
          sign-key: "SECcd6xxxxxxxxxxxxxxxxxxxxxxx67c82fe811656bdd0"

